### ISSUE TITLE
Add custom stop command and stop signals

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-hooks-code#30]
Currently, web and worker processes are stopped by runit sending the SIGQUIT term signal. In some cases, like workers for example, the process needs a bit of time to clean up or at least needs to be informed that it's going to be killed.

Here's a potential way this can be handled:

```
worker.main:
  start: sidekiq
  stop: sidekiq-stop
```

There are some problems with this approach, such as when there are multiple starts, so this needs some additional thought.

Here are some references to how we can customize runit for this task:
- https://serverfault.com/questions/410331/how-to-write-runit-custom-stop-script

**Comment by tylerflint** [comment]
After some discussion, it appears there is a pattern here that can work:

```
web.main:
  start: start-command
  stop: stop-command
  stop_force: true
  stop_wait: 60

worker.main:
  start:
    foo: start-command
    bar: start-command
  stop:
    foo: stop-command
  stop_force:
    bar: true
  stop_wait:
    foo: 60
```

Since we spent so much time building that awesome boxfile validation framework, we can create a validator that ensures that:
- the stop* structure matches the start structure (ie: string, hash, etc)
- if stop* statements are declared, the start commands cannot be listed as an array
