### ISSUE TITLE
Chown writable dir if already exists

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-hooks-code#35]
[Currently](https://github.com/nanobox-io/nanobox-hooks-code/blob/master/src/configure#L107), writable dirs are only created/chowned if they don't already exist. We should probably chown them if they do already exist.

To reproduce:
```yml
run.config:
  engine: none

deploy.config:
  before_live:
    web.main:
      - mkdir -p /app/var/cache  

web.main:
  log_watch:
    thing: /app/var/log/thing.log
  writable_dirs:
    - var
  start: sleep 1d
```

Then `nanobox deploy dry-run`

The log watch directory get created first, as root, and the `/app/var` doesn't get `chown`ed because it already exists.

**Comment by glinton** [comment]
A workaround for now would be to add the following `before_live` hook into your `boxfile.yml`: `sudo chown gonano /app/var`. 

The complete workaround boxfile is:
```yml
run.config:
  engine: none

deploy.config:
  before_live:
    web.main:
      - sudo chown gonano /app/var
      - mkdir -p /app/var/cache  

web.main:
  log_watch:
    thing: /app/var/log/thing.log
  writable_dirs:
    - var
  start: sleep 1d
```
